//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Branch()
        {
            this.DailyHistory = new HashSet<DailyHistory>();
            this.Schedule = new HashSet<Schedule>();
            this.SubModule = new HashSet<SubModule>();
        }
    
        public System.Guid Id { get; set; }
        public string Address { get; set; }
        public System.Guid CityId { get; set; }
        public System.Guid RegionId { get; set; }
        public System.Guid GymId { get; set; }
        public System.Guid BranchDaily_BranchId { get; set; }
        public System.Guid AccessMethodId { get; set; }
    
        public virtual AccessMethodType AccessMethodType { get; set; }
        public virtual Daily Daily { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyHistory> DailyHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubModule> SubModule { get; set; }
        public virtual Gym Gym { get; set; }
    }
}
