//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeUser()
        {
            this.JourneyEmployee = new HashSet<JourneyEmployee>();
            this.User = new HashSet<User>();
        }
    
        public System.Guid Id { get; set; }
        public string ARL { get; set; }
        public string PensionFund { get; set; }
        public System.DateTime StartContract { get; set; }
        public Nullable<System.DateTime> EndContract { get; set; }
        public string BankId { get; set; }
        public string AccountType { get; set; }
        public string AccountNumber { get; set; }
        public string Salary { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public string Ip { get; set; }
        public bool IsActive { get; set; }
        public System.Guid EmployeeType_Id { get; set; }
    
        public virtual EmployeeType EmployeeType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JourneyEmployee> JourneyEmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User { get; set; }
    }
}
