//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GymmetryEntities3 : DbContext
    {
        public GymmetryEntities3()
            : base("name=GymmetryEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<AccessMethodType> AccessMethodType { get; set; }
        public virtual DbSet<Bill> Bill { get; set; }
        public virtual DbSet<Branch> Branch { get; set; }
        public virtual DbSet<Brand> Brand { get; set; }
        public virtual DbSet<CategoryExercise> CategoryExercise { get; set; }
        public virtual DbSet<Daily> Daily { get; set; }
        public virtual DbSet<DailyExercise> DailyExercise { get; set; }
        public virtual DbSet<DailyExerciseHistory> DailyExerciseHistory { get; set; }
        public virtual DbSet<DailyHistory> DailyHistory { get; set; }
        public virtual DbSet<Diet> Diet { get; set; }
        public virtual DbSet<EmployeeRegisterDaily> EmployeeRegisterDaily { get; set; }
        public virtual DbSet<EmployeeType> EmployeeType { get; set; }
        public virtual DbSet<EmployeeUser> EmployeeUser { get; set; }
        public virtual DbSet<Exercise> Exercise { get; set; }
        public virtual DbSet<FitUser> FitUser { get; set; }
        public virtual DbSet<Gym> Gym { get; set; }
        public virtual DbSet<GymPlanSelected> GymPlanSelected { get; set; }
        public virtual DbSet<GymPlanSelectedModule> GymPlanSelectedModule { get; set; }
        public virtual DbSet<GymPlanSelectedType> GymPlanSelectedType { get; set; }
        public virtual DbSet<GymTypes> GymTypes { get; set; }
        public virtual DbSet<JourneyEmployee> JourneyEmployee { get; set; }
        public virtual DbSet<LogChanges> LogChanges { get; set; }
        public virtual DbSet<LogErrors> LogErrors { get; set; }
        public virtual DbSet<LogLogin> LogLogin { get; set; }
        public virtual DbSet<LogUninstall> LogUninstall { get; set; }
        public virtual DbSet<Machine> Machine { get; set; }
        public virtual DbSet<MachineCategory> MachineCategory { get; set; }
        public virtual DbSet<Module> Module { get; set; }
        public virtual DbSet<Notification> Notification { get; set; }
        public virtual DbSet<NotificationOption> NotificationOption { get; set; }
        public virtual DbSet<Permissions> Permissions { get; set; }
        public virtual DbSet<PhysicalAssessment> PhysicalAssessment { get; set; }
        public virtual DbSet<Plan> Plan { get; set; }
        public virtual DbSet<PlanType> PlanType { get; set; }
        public virtual DbSet<RoutineAssigned> RoutineAssigned { get; set; }
        public virtual DbSet<RoutineExercise> RoutineExercise { get; set; }
        public virtual DbSet<RoutineTemplate> RoutineTemplate { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<SubModule> SubModule { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UninstallOptions> UninstallOptions { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserType> UserType { get; set; }
    }
}
