//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoutineTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoutineTemplate()
        {
            this.RoutineExercise = new HashSet<RoutineExercise>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Comments { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public string Ip { get; set; }
        public bool IsActive { get; set; }
        public System.Guid GymId { get; set; }
        public System.Guid RoutineUser_RoutineId { get; set; }
        public System.Guid RoutineAssignedId { get; set; }
    
        public virtual Gym Gym { get; set; }
        public virtual RoutineAssigned RoutineAssigned { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoutineExercise> RoutineExercise { get; set; }
        public virtual User User { get; set; }
    }
}
