//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoutineExercise
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoutineExercise()
        {
            this.Daily = new HashSet<Daily>();
            this.DailyHistory = new HashSet<DailyHistory>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public string Ip { get; set; }
        public bool IsActive { get; set; }
        public string Sets { get; set; }
        public string Repetitions { get; set; }
        public System.Guid RoutineTemplateId { get; set; }
        public System.Guid ExerciseId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Daily> Daily { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyHistory> DailyHistory { get; set; }
        public virtual Exercise Exercise { get; set; }
        public virtual RoutineTemplate RoutineTemplate { get; set; }
    }
}
