//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Bill = new HashSet<Bill>();
            this.Bill1 = new HashSet<Bill>();
            this.Daily = new HashSet<Daily>();
            this.DailyHistory = new HashSet<DailyHistory>();
            this.Diet = new HashSet<Diet>();
            this.LogChanges = new HashSet<LogChanges>();
            this.LogErrors = new HashSet<LogErrors>();
            this.LogLogin = new HashSet<LogLogin>();
            this.LogUninstall = new HashSet<LogUninstall>();
            this.Notification = new HashSet<Notification>();
            this.NotificationOption = new HashSet<NotificationOption>();
            this.Permissions = new HashSet<Permissions>();
            this.PhysicalAssessment = new HashSet<PhysicalAssessment>();
            this.RoutineAssigned = new HashSet<RoutineAssigned>();
            this.RoutineTemplate = new HashSet<RoutineTemplate>();
        }
    
        public System.Guid Id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<System.Guid> IdEPS { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public Nullable<System.Guid> IdGender { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string ProfileImageUrl { get; set; }
        public Nullable<System.Guid> DocumentTypeId { get; set; }
        public string DocumentType { get; set; }
        public string Phone { get; set; }
        public Nullable<System.Guid> CountryId { get; set; }
        public string Address { get; set; }
        public Nullable<System.Guid> CityId { get; set; }
        public Nullable<System.Guid> RegionId { get; set; }
        public string RH { get; set; }
        public string EmergencyName { get; set; }
        public string EmergencyPhone { get; set; }
        public string PhysicalExceptions { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public string Ip { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.Guid> GymId { get; set; }
        public Nullable<System.Guid> UserTypeId { get; set; }
        public Nullable<System.Guid> PlanId { get; set; }
        public Nullable<System.Guid> UserFitUser_UserId { get; set; }
        public Nullable<System.Guid> UserDiet_UserId { get; set; }
        public Nullable<System.Guid> UserGym_UserId { get; set; }
        public Nullable<System.Guid> EmployeeRegisterDailyUser_UserId { get; set; }
        public Nullable<System.Guid> ScheduleUser_UserId { get; set; }
        public Nullable<System.Guid> UserEmployeeUser_UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bill1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Daily> Daily { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyHistory> DailyHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diet> Diet { get; set; }
        public virtual Diet Diet1 { get; set; }
        public virtual EmployeeRegisterDaily EmployeeRegisterDaily { get; set; }
        public virtual EmployeeUser EmployeeUser { get; set; }
        public virtual FitUser FitUser { get; set; }
        public virtual Gym Gym { get; set; }
        public virtual Gym Gym1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogChanges> LogChanges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogErrors> LogErrors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogLogin> LogLogin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogUninstall> LogUninstall { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationOption> NotificationOption { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Permissions> Permissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhysicalAssessment> PhysicalAssessment { get; set; }
        public virtual Plan Plan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoutineAssigned> RoutineAssigned { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoutineTemplate> RoutineTemplate { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
